### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by sniff122** [bitluni/luniASM#1]
Why doesn't it work! I need it to work!

**Comment by Handkep** [comment]
It doesnt work for me neither!

**Comment by andyvanee** [comment]
I haven't tried the C++ version yet, but the web version works fine for me. I assume this issue is about not knowing how to run a local HTTP server?

```sh
# If you have python3 installed
python3 -m http.server 8080

# If you have node installed
npx http-server -p 8080
```

With either of these running you should be able to visit <http://localhost:8080/IDE.html> or <http://127.0.0.1:8080/IDE.html> and see the interactive editor.

**Comment by lewis-foster-reciteme** [comment]
Just for context, this was just a joke issue I created before any code was pushed

**Comment by bitluni** [comment]
trolls :-)
of course it doesn't. I made it
